config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "homes#top"
  get '/admin', to: 'admin/homes#top'
  get  '/home/about', to: 'homes#about', as: 'about'


  namespace :admin do
    resources :genre, only: [:index, :create, :edit, :update]
    resources :orders_detail, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :homes, only: [:top]
  end

  namespace :public do
    post 'orders/confirm'
    get 'orders/complete'
    delete 'cart_items/destroy_all'
    get 'customers/confirm'
    patch 'customers/withdraw'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :cart_items, only: [:index, :create, :destroy, :update]
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    "〒" + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def full_name
    last_name + ' ' + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  has_many :order_detail, dependent: :destroy
  has_many :cart_item, dependent: :destroy
  belongs_to :genre, optional: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { awaiting_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4 }

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  def full_address
    postal_code + ' ' + address + ' ' + name
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  enum making_status: { production_cannot: 0, awaiting_manufacture: 1, in_production: 2, completed_production: 3 }

  belongs_to :item
  belongs_to :order
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end
end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :postal_code, :address, :email, :is_deleted)
  end

app/controllers/admin/genre_controller.rb
class Admin::GenreController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genre_index_path(@genre.id)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genre_index_path(@genre.id)
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all

  end

  def new
    @item = Item.new
    @genre = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_detail_helper.rb
module Admin::OrdersDetailHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <td><%= @customer.last_name%><%= @customer.first_name%>さんの会員情報編集</td>
          </tr>
        </thead>

        <tbody>
          <%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>

          <tr>
            <td>氏名</td>
            <td>
              <%= f.text_field :last_name %>
              <%= f.text_field :first_name %>
            </td>
          </tr>

          <tr>
            <td>フリガナ</td>
            <td>
              <%= f.text_field :last_name_kana %>
              <%= f.text_field :first_name_kana %>
            </td>
          </tr>

          <tr>
            <td>郵便番号</td>
            <td><%= f.text_field :postal_code %></td>
          </tr>

          <tr>
            <td>住所</td>
            <td><%= f.text_field :address %></td>
          </tr>

          <tr>
            <td>電話番号</td>
            <td><%= f.text_field :telephone_number %></td>
          </tr>

          <tr>
            <td>メールアドレス</td>
            <td><%= f.text_field :email %></td>
          </tr>

          <tr>
            <td>販売ステータス</td>
            <td>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, "有効", {value: true, style: "display: inline-block;"} %>
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, "退会", {value: false, style: "display: inline-block;"} %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-md-5 offset-md-2">
    <p><%= f.submit '変更を保存' %></p>
  </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 offset-md-2">
      <p>会員一覧</p>
    </div>
  </div>

    <div class="col-md-8 offset-md-2">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td>
              <%= customer.id %>
            </td>

            <td>
              <%= link_to customer.last_name, admin_customer_path(customer.id) %>
              <%= customer.first_name%>
            </td>

            <td><%= customer.email %></td>

            <td>
              <% if customer.is_deleted%>
              有効
              <% else %>
              退会
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
          <td><%= @customer.last_name%><%= @customer.first_name%>さんの会員紹介</td>
          </tr>
        </thead>
        <tbody>
          <tr><td>会員ID</td><td><%= @customer.id %></td></tr>
          <tr><td>氏名</td><td><%= @customer.last_name %><%= @customer.first_name %></td></tr>
          <tr><td>フリガナ</td><td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td></tr>
          <tr><td>郵便番号</td><td><%= @customer.postal_code %></td></tr>
          <tr><td>住所</td><td><%= @customer.address %></td></tr>
          <tr><td>電話番号</td><td><%= @customer.telephone_number %></td></tr>
          <tr><td>メールアドレス</td><td><%= @customer.email %></td></tr>
          <tr><td>会員ステータス</td>
              <td>
                <% if @customer.is_deleted %>
                有効
                <% else %>
                退会
                <% end %>
              </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-md-5 offset-md-2">
    <%= link_to "編集する" , edit_admin_customer_path(@customer.id) %>
    <%= link_to "注文履歴一覧を見る" , admin_path %>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>