config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "homes#top"
  get '/admin', to: 'admin/homes#top'
  get  '/home/about', to: 'homes#about', as: 'about'


  namespace :admin do
    resources :genre, only: [:index, :create, :edit, :update]
    resources :orders_detail, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :homes, only: [:top]
  end

  namespace :public do
    post 'orders/confirm'
    get 'orders/complete'
    delete 'cart_items/destroy_all'
    get 'customers/confirm'
    patch 'customers/withdraw'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :cart_items, only: [:index, :create, :destroy, :update]
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    "〒" + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def full_name
    last_name + ' ' + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  has_many :order_detail, dependent: :destroy
  has_many :cart_item, dependent: :destroy
  belongs_to :genre, optional: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { awaiting_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4 }

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  def full_address
    postal_code + ' ' + address + ' ' + name
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  enum making_status: { production_cannot: 0, awaiting_manufacture: 1, in_production: 2, completed_production: 3 }

  belongs_to :item
  belongs_to :order
end

app/controllers/admin/genre_controller.rb
class Admin::GenreController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genre_index_path(@genre.id)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genre_index_path(@genre.id)
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all

  end

  def new
    @item = Item.new
    @genre = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details
    if @order.payment_confirmation?
      puts "hello"
      @order_details.each do |order_detail|
      order_detail.awaiting_manufacture!
      end
    end
    redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :created_at, :postal_code, :address, :name, :payment_method, :status,:shipping_cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_detail_helper.rb
module Admin::OrdersDetailHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genre/create.html.erb
<h1>Admin::Genre#create</h1>
<p>Find me in app/views/admin/genre/create.html.erb</p>

app/views/admin/genre/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 offset-md-1">
      <p>ジャンル編集</p>
    </div>
  </div>

    <div class="col-md-5">
      <%= form_with model: @genre, url: admin_genre_path(@genre) do |f| %>
      <div>
        ジャンル名
        <%= f.text_field :name %>
        <%= f.submit '変更を保存' %>
      </div>
      <% end %>
    </div>
</div>

app/views/admin/genre/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 offset-md-1">
      <p>ジャンル一覧・追加</p>
    </div>
  </div>

    <div class="col-md-5">
      <%= form_with model: @genre, url: admin_genre_index_path do |f| %>
      <tr>
      ジャンル名
      <%= f.text_field :name %>
      <%= f.submit '新規登録' %>
      <% end %>
      </tr>
    </div>

    <div class="col-md-5">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>ジャンル名</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td>
              <%= link_to "編集する" , edit_admin_genre_path(genre.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/genre/update.html.erb
<h1>Admin::Genre#update</h1>
<p>Find me in app/views/admin/genre/update.html.erb</p>

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<div class="container px-5">
  <div class="row">
    <div class="col-md-7 offset-md-1">
      <p>商品編集</p>
    </div>

    <div class="col-md-7">

      <%= form_with model: @item, url: admin_item_path(@item) do |f| %>

      <p>商品画像
        <%= f.file_field :image, accept: "image/*" %>
      </p>

      <p>商品名
        <%= f.text_field :name %>
      </p>

      <p>商品説明
        <%= f.text_area :introduction %>
      </p>

      <p>ジャンル
      <%= f.collection_select(:genre_id, @genres, :id, :name) %>
      </p>

      <p>税抜価格
        <%= f.text_area :price %>円
      </p>

      <p>販売ステータス
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, "販売中", {value: true, style: "display: inline-block;"} %>
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, "販売停止", {value: false, style: "display: inline-block;"} %>
      </p>

      <p><%= f.submit '変更を保存' %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 ">
      <h1>商品一覧</h1>
    </div>

    <div class="col-md-10 offset-md-7">
      <p>
        <%= link_to new_admin_item_path, class: "nav-link" do %>
        <i class="fas fa-plus-circle"></i>
        <%end%>
      </p>
    </div>

    <div class="col-md-10 ">
      <table class="table table-hover table-inverse">

        <thead>
          <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td>
              <%= item.id %>
            </td>
            <td>
              <%= link_to item.name , admin_item_path(item.id) %>
            </td>
            <td>
              <%= item.price %>
            </td>
            <td>
              <%= item.genre.name %>
            </td>
            <td>
              <% if item.is_active %>
              販売中
              <% else %>
              販売停止中
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <h1>商品新規登録</h1>
    </div>

    <div class="col-md-7 offset-md-2">
  <%= form_with model: @item, url: admin_items_path do |f| %>

    <p>商品画像
      <%= f.file_field :image, accept: "image/*" %>
    </p>

    <p>商品名
      <%= f.text_field :name %>
    </p>

    <p>商品説明
      <%= f.text_area :introduction %>
    </p>

    <p>ジャンル
    <%= f.collection_select(:genre_id, @genre, :id, :name) %>
    </p>

    <p>税抜価格
      <%= f.text_area :price %>円
    </p>

    <p>販売ステータス
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, "販売中" %>
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, "販売停止" %>
    </p>

    <p><%= f.submit '新規登録' %></p>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3<div class= offset-md-1">
      <p>商品詳細</p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <p><%= image_tag @item.get_image(200,200) %></p>
    </div>

    <div class="col-md-5">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>商品名</td><td><%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td><td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td>税込価格(税抜価格)</td>
            <td>
              <% @price=@item.price %>
              <% @price*=1.1 %>
              <%= @price.round %>
              (<%= @item.price %>)
            </td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <td>
              <% if @item.is_active %>
              販売中
              <% else %>
              販売停止中
              <% end %>
            </td>
          </tr>
          <tr>
            <td>
              <%= link_to "編集する" , edit_admin_item_path(@item.id) %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
    <br>
    <h2>注文履歴詳細</h2>
    <br>
    <p>購入者：<%= @order.customer.full_name %></p>
    <p>注文日：<%= @order.created_at.strftime('%Y/%m/%d') %></p>
    <p>配送先：<%= @order.full_address %></p>
    <p>支払方法：<%= @order.payment_method_i18n %></p>
    <p>
      <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
      注文ステータス：
      <%= f.select :status, Order.statuses.keys.map { |k| [I18n.t("enums.order.status.#{k}"),k]} %>
      <%= f.submit '更新' %>
      <% end %>
    </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <table class="table">
        <thead>
          <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          </tr>
        </thead>
        <% @price_subtotal2=0 %>
        <% @order_details.each do |order_detail| %>
        <tbody>
          <tr>
            <td>
              <%= order_detail.item.name %>
            </td>
            <td>
              <% @price=order_detail.price %>
              <% @price*=1.1 %>
              <%= @price.round %>
            </td>
            <td>
              <%= order_detail.amount %>
            </td>
            <td>
              <% @price_subtotal=@price %>
              <% @price_subtotal*=order_detail.amount %>
              <%= @price_subtotal.round %>
            </td>
            <td>
              <%= form_with model: order_detail, url: admin_orders_detail_path(order_detail.id), method: :patch do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |k| [I18n.t("enums.order_detail.making_status.#{k}"),k]} %>
              <%= f.submit '更新' %>
              <% end %>
            </td>
          </tr>
        </tbody>
        <% @price_subtotal2+=@price_subtotal %>
        <% end %>
      </table>
    </div>
    <div class="col-md-4">
      <br>
      <br>
      <p>
        商品合計：
        <%= @price_subtotal2.round %>
      </p>
      <p>
        送料：
        <%= @order.shipping_cost %>
      </p>
      <p>
        請求金額合計：
        <%= @order.total_payment %>
      </p>
    </div>
  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>