config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: "homes#top"
  get '/admin', to: 'admin/homes#top'
  get  '/home/about', to: 'homes#about', as: 'about'


  namespace :admin do
    resources :genre, only: [:index, :create, :edit, :update]
    resources :orders_detail, only: [:update]
    resources :orders, only: [:show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :homes, only: [:top]
  end

  namespace :public do
    post 'orders/confirm'
    get 'orders/complete'
    delete 'cart_items/destroy_all'
    get 'customers/confirm'
    patch 'customers/withdraw'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :cart_items, only: [:index, :create, :destroy, :update]
    resource :customers, only: [:show, :edit, :update]
    resources :items, only: [:index, :show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    "〒" + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def full_name
    last_name + ' ' + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  has_many :order_detail, dependent: :destroy
  has_many :cart_item, dependent: :destroy
  belongs_to :genre, optional: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { awaiting_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4 }

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  def full_address
    postal_code + ' ' + address + ' ' + name
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  enum making_status: { production_cannot: 0, awaiting_manufacture: 1, in_production: 2, completed_production: 3 }

  belongs_to :item
  belongs_to :order
end

app/controllers/admin/genre_controller.rb
class Admin::GenreController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genre_index_path(@genre.id)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genre_index_path(@genre.id)
  end


  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genre_helper.rb
module Admin::GenreHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar">
        <div class="container">
          <%= link_to root_path do%>
          <%= image_tag 'cake', size: "50x50" %>
          <% end %>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>

              <div class="mr-3">
                <li>
                  <%= link_to "マイページ", public_customers_path %>
                </li>
              </div>

              <div class="mr-3">
                <li>
                  <%= link_to "商品一覧", public_items_path %>
                </li>
              </div>

              <div class="mr-3">
                <li>
                  <%= link_to "カート", public_cart_items_path %>
                </li>
              </div>

              <div class="mr-3">
                <li>
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
                </li>
              </div>

              <% elsif admin_signed_in? %>
              <div class="mr-3">
                <li>
                  <%= link_to "商品一覧", admin_items_path %>
                </li>
              </div>

              <div class="mr-3">
                <li>
                  <%= link_to "会員一覧", admin_customers_path  %>
                </li>
              </div>

              <div class="mr-3">
                <li>
                  <%= link_to "注文履歴一覧", admin_path %>
                </li>
              </div>

              <div class="mr-3">
                <li>
                  <%= link_to "ジャンル一覧", admin_genre_index_path %>
                </li>
              </div>

              <div class="mr-3">
                <li>
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
                </li>
              </div>

              <% else %>
              <div class="mr-3">
                <li>
                  <%= link_to "About", about_path %>
                </li>
              </div>

              <div class="mr-3">
                <li>
                  <%= link_to "商品一覧", public_items_path %>
                </li>
              </div>

              <div class="mr-3">
                <li>
                  <%= link_to "新規登録", new_customer_registration_path %>
                </li>
              </div>

              <div class="mr-3">
                <li>
                  <%= link_to "ログイン", new_customer_session_path %>
                </li>
              </div>

              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>